# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('postcode', models.TextField()),
                ('city', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Atmosphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, b'Not Good'), (2, b'OK'), (3, b'Good'), (4, b'Very Good'), (5, b'Excellent')], default=5, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='london_cafes.Address')),
                ('atmosphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='london_cafes.Atmosphere')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, b'Not Good'), (2, b'OK'), (3, b'Good'), (4, b'Very Good'), (5, b'Excellent')], default=5, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, b'Not Good'), (2, b'OK'), (3, b'Good'), (4, b'Very Good'), (5, b'Excellent')], default=5, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cafe',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='london_cafes.Coffee'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='wifi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='london_cafes.Wifi'),
        ),
    ]
