# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-26 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('london_cafes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='atmosphere',
            new_name='atmosphere_rating',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='coffee',
            new_name='coffee_rating',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='wifi',
            new_name='wifi_rating',
        ),
    ]
