# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_cafes', '0003_removed_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='address',
        ),
        migrations.AddField(
            model_name='cafe',
            name='address1',
            field=models.CharField(default='address1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='address2',
            field=models.CharField(default='address2', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='address3',
            field=models.CharField(default='address3', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.CharField(default='city', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='post_code',
            field=models.CharField(default='postcode', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
