# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('london_cafes', '0004_moved_address_fields_to_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, b'Not Good'), (2, b'OK'), (3, b'Good'), (4, b'Very Good'), (5, b'Excellent')], default=5, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cafe',
            name='atmosphere_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmosphere_rating', to='london_cafes.Ratings'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='coffee_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_rating', to='london_cafes.Ratings'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='wifi_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_rating', to='london_cafes.Ratings'),
        ),
        migrations.DeleteModel(
            name='Atmosphere',
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='Wifi',
        ),
    ]
