# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('london_cafes', '0005_removed_atmosphere_wifi_coffee_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
